name: jenn
channels:
- conda-forge
- defaults
dependencies:
  - python >=3.11,<3.12
  # build
  - doit[toml]
  - conda-lock
  - python-dotenv
  - build 
  - twine 
  - pip 
  # protyping
  - jupyterlab >=3.6,<4.0.0a0
  # lint
  - black ==23.1.0
  - docformatter ==1.5.1
  - lxml
  - mypy 
  - ruff 
  # test
  - pytest
  - pytest-cov
  - pytest-html
  # docs
  - sphinx 
  - sphinx_rtd_theme 
  - sphinx-multiversion
  # runtime
  - numpy 
  - orjson 
  - matplotlib-base
