name: jenn-build-test-deploy
run-name: ${{ github.actor }} is learning GitHub Actions

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["refactor"]


jobs:
  doit:
    name: doit
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create base environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: deploy/specs/base.yml
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Create runtime environment
        shell: bash -el {0}
        run: | 
          doit env 
      - name: Build app
        shell: bash -el {0}
        run: | 
          doit install 
      - name: Test app
        shell: bash -el {0}
        run: | 
          doit test 
      - name: Build docs
        shell: bash -el {0}
        run: | 
          doit docs 
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './build/docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4