name: jenn-ci
run-name: ${{ github.actor }}-jenn-ci

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ master ]


jobs:
  qa:
    uses: ./.github/workflows/.github-ci-qa.yml
  test:
    needs: qa
    uses: ./.github/workflows/.github-ci-test.yml
  deploy: 
    needs: test
    uses: ./.github/workflows/.github-ci-docs.yml
