name: jenn-ci-qa
run-name: ${{ github.actor }}-jenn-ci-qa

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create base environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: deploy/specs/base.yml 
      - name: Packaging
        shell: bash -el {0}
        run: | 
          doit package
      - name: Store wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./build/dist/*.whl
      - name: Store source artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: ./build/dist/*.tar.gz
    