name: jenn-ci-dev
run-name: ${{ github.actor }}-jenn-ci-dev

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on: [push]

jobs:
  qa:
    uses: ./.github/workflows/.github-ci-qa.yml
  run:
    uses: ./.github/workflows/.github-ci-test.yml
